package com.hibernate.world.entities;

// Generated Nov 29, 2013 10:57:52 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Countrylanguage generated by hbm2java
 */
@Entity
@Table(name = "countrylanguage", catalog = "world")
public class Countrylanguage implements java.io.Serializable {

	private CountrylanguageId id;
	private String isOfficial;
	private float percentage;

	public Countrylanguage() {
	}

	public Countrylanguage(CountrylanguageId id, String isOfficial,
			float percentage) {
		this.id = id;
		this.isOfficial = isOfficial;
		this.percentage = percentage;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "countryCode", column = @Column(name = "CountryCode", nullable = false, length = 3)),
			@AttributeOverride(name = "language", column = @Column(name = "Language", nullable = false, length = 30)) })
	public CountrylanguageId getId() {
		return this.id;
	}

	public void setId(CountrylanguageId id) {
		this.id = id;
	}

	@Column(name = "IsOfficial", nullable = false, length = 2)
	public String getIsOfficial() {
		return this.isOfficial;
	}

	public void setIsOfficial(String isOfficial) {
		this.isOfficial = isOfficial;
	}

	@Column(name = "Percentage", nullable = false, precision = 4, scale = 1)
	public float getPercentage() {
		return this.percentage;
	}

	public void setPercentage(float percentage) {
		this.percentage = percentage;
	}

}
